post checking status

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -73,4 +73,15 @@ runs:
           esac
 
           echo "⏁  Removing Runner from ZeroTier network"
-          curl -s -X DELETE -H "Authorization: token ${{ inputs.auth_token }}" "${{ inputs.api_url }}/network/${{ inputs.network_id }}/member/${member_id}"
+          curl -i -s -X DELETE -H "Authorization: token ${{ inputs.auth_token }}" "${{ inputs.api_url }}/network/${{ inputs.network_id }}/member/${member_id}" > /tmp/api_delete_output.txt
+          STATUS_CODE=$(cat /tmp/api_delete_output.txt | grep 'HTTP/' | awk '{print $2}')
+
+          if [[ $STATUS_CODE -ge 400 && $STATUS_CODE -le 599 ]]; then
+              echo "Error! Status code: $STATUS_CODE"
+              echo "Response: $(cat /tmp/api_delete_output.txt)"
+              exit $STATUS_CODE
+          
+          else
+              echo "Success! Status code: $STATUS_CODE"
+              exit 0
+          fi
